export const FETCH_AUTH_USER_LIST_START = 'FETCH_AUTH_USER_LIST_START';
export const FETCH_AUTH_USER_LIST_SUCCESS = 'FETCH_AUTH_USER_LIST_SUCCESS';
export const FETCH_AUTH_USER_DETAIL_SUCCESS = 'FETCH_AUTH_USER_DETAIL_SUCCESS';
export const FETCH_AUTH_UPDATE_SUCCESS = 'FETCH_AUTH_UPDATE_SUCCESS';
