export const FETCH_USER_LIST_STARTED = 'FETCH_USER_LIST_STARTED';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_UPDATE_USER_SUCCESS = 'FETCH_UPDATE_USER_SUCCESS';
export const FETCH_USER_LOGS_STARTED = 'FETCH_USER_LOGS_STARTED';
export const FETCH_USER_LOGS_SUCCESS = 'FETCH_USER_LOGS_SUCCESS';
