export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_LOGS_LIST_STARTED = 'FETCH_LOGS_LIST_STARTED';
export const FETCH_LOGS_LIST_SUCCESS = 'FETCH_LOGS_LIST_SUCCESS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
